In [15]:
import csv
import os
import matplotlib.pyplot as plt 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import svm 
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn import preprocessing
import pandas as pd

## Importing and Reading the data

In [16]:
path = '/home/deep/Workspace/Customer_Behavior/Dataset.csv'
data = pd.read_csv(path)
data.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

## Label Encoding of Features

In [17]:
lb_make = LabelEncoder()
label_df = pd.DataFrame()
label_df['Gender_Code'] = lb_make.fit_transform(data['gender'])
label_df['Partner_Code'] = lb_make.fit_transform(data['Partner'])
label_df['Dependents_Code'] = lb_make.fit_transform(data['Dependents'])
label_df['PhoneService_Code'] = lb_make.fit_transform(data['PhoneService'])
label_df['MultipleLines_Code'] = lb_make.fit_transform(data['MultipleLines'])
label_df['InternetService_Code'] = lb_make.fit_transform(data['InternetService'])
label_df['OnlineSecurity_Code'] = lb_make.fit_transform(data['OnlineSecurity'])
label_df['OnlineBackup_Code'] = lb_make.fit_transform(data['OnlineBackup'])
label_df['DeviceProtection_Code'] = lb_make.fit_transform(data['DeviceProtection'])
label_df['TechSupport_Code'] = lb_make.fit_transform(data['TechSupport'])
label_df['StreamingTV_Code'] = lb_make.fit_transform(data['StreamingTV'])
label_df['StreamingMovies_Code'] = lb_make.fit_transform(data['StreamingMovies'])
label_df['Contract_Code'] = lb_make.fit_transform(data['Contract'])
label_df['PaperlessBilling_Code'] = lb_make.fit_transform(data['PaperlessBilling'])
label_df['PaymentMethod_Code'] = lb_make.fit_transform(data['PaymentMethod'])
label_df['Churn_Code'] = lb_make.fit_transform(data['Churn'])

## One Hot Encoding of Label Encoded Features

In [18]:
data_df = pd.DataFrame()
y = pd.get_dummies(label_df['Gender_Code'])
x = pd.get_dummies(label_df['Partner_Code'])
z = pd.get_dummies(label_df['Dependents_Code'])
a = pd.get_dummies(label_df['PhoneService_Code'])
b = pd.get_dummies(label_df['MultipleLines_Code'])
c = pd.get_dummies(label_df['InternetService_Code'])
d = pd.get_dummies(label_df['OnlineSecurity_Code'])
e = pd.get_dummies(label_df['OnlineBackup_Code'])
f = pd.get_dummies(label_df['DeviceProtection_Code'])
g = pd.get_dummies(label_df['TechSupport_Code'])
h = pd.get_dummies(label_df['StreamingTV_Code'])
i = pd.get_dummies(label_df['StreamingMovies_Code'])
j = pd.get_dummies(label_df['Contract_Code'])
k = pd.get_dummies(label_df['PaperlessBilling_Code'])
l = pd.get_dummies(label_df['PaymentMethod_Code'])

In [19]:
data['MonthlyCharges'] = data['MonthlyCharges'].astype(int)
data['TotalCharges'] = pd.to_numeric(data['TotalCharges'])
data['TotalCharges'] = data['TotalCharges'].astype(int)

## Putting all the feature together in one DataFrame

In [20]:
data_df['Gender_Female'] = y[0]
data_df['Gender_Male'] = y[1]
data_df['Senior_Citizen'] = data['SeniorCitizen']
data_df['Partner_Yes'] = x[0]
data_df['Partner_No'] = x[1]
data_df['Dependents_Yes'] = z[1]
data_df['Dependents_No'] = z[0]
data_df['Tenure'] = data['tenure']
data_df['PhoneService_Yes'] = a[1]
data_df['PhoneService_No'] = a[0]
data_df['MultipleLines_NoPhnServ'] = b[1]
data_df['MultipleLines_Yes'] = b[2]
data_df['MultipleLines_No'] = b[0]
data_df['InternetService_DSL'] = c[0]
data_df['InternetService_FiberOptic'] = c[1]
data_df['InternetService_No']= c[2]
data_df['OnlineSecurity_Yes'] = d[2]
data_df['OnlineSecurity_No'] = d[0]
data_df['OnlineSecurity_NoInternetService'] = d[1]
data_df['OnlineBackup_Yes'] = e[2]
data_df['OnlineBackup_No'] = e[0]
data_df['OnlineBackup_NoInternetService'] = e[1]
data_df['DeviceProtection_Yes'] = f[2]
data_df['DeviceProtection_No'] = f[0]
data_df['DeviceProtection_NoInternetService'] = f[1]
data_df['TechSupport_Yes'] = g[2]
data_df['TechSupport_No']= g[0]
data_df['TechSupport_NoInternetService'] = g[1]
data_df['StreamingTV_Yes'] = h[2]
data_df['StreamingTV_No'] = h[0]
data_df['StreamingTV_NoInternetService'] = h[1]
data_df['StreamingMovies_Yes'] = i[2]
data_df['StreamingMovies_No'] = i[0]
data_df['StreamingMovies_NoInternetService']= i[1]
data_df['Contract_Monthly'] = j[0]
data_df['Contract_Yearly'] = j[1]
data_df['Contract_TwoYearly'] = j[2]
data_df['PaperlessBilling_Yes'] = k[1]
data_df['PaperlessBilling_No'] = k[0]
data_df['PaymentMethod_Electronic'] = l[2]
data_df['PaymentMethod_Mail'] = l[3]
data_df['PaymentMethod_Bank'] = l[0]
data_df['PaymentMethod_Credit'] = l[1]
data_df['MonthlyCharges'] = data['MonthlyCharges']
data_df['TotalCharges'] = data['TotalCharges']

## Splitting Testing and Training Data

In [21]:
X_train, X_test, y_train, y_test = train_test_split(data_df, label_df['Churn_Code'], test_size=0.25)

In [22]:
data_df.describe()

,Gender_Female,Gender_Male,Senior_Citizen,Partner_Yes,Partner_No,Dependents_Yes,Dependents_No,Tenure,PhoneService_Yes,PhoneService_No,...,Contract_Yearly,Contract_TwoYearly,PaperlessBilling_Yes,PaperlessBilling_No,PaymentMethod_Electronic,PaymentMethod_Mail,PaymentMethod_Bank,PaymentMethod_Credit,MonthlyCharges,TotalCharges
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,...,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,0.495244,0.504756,0.162147,0.516967,0.483033,0.299588,0.700412,32.371149,0.903166,0.096834,...,0.209144,0.240664,0.592219,0.407781,0.335794,0.228880,0.219225,0.216101,64.295897,2280.528184
std,0.500013,0.500013,0.368612,0.499748,0.499748,0.458110,0.458110,24.559481,0.295752,0.295752,...,0.406726,0.427517,0.491457,0.491457,0.472301,0.420141,0.413751,0.411613,30.092727,2265.745655
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,18.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.000000,401.500000
50%,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,29.000000,1.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,70.000000,1394.000000
75%,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,55.000000,1.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,89.000000,3786.500000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,118.000000,8684.000000

### As we can see that the min and max values of the features vary. This will wrong results if the same will be used to fit the model. To bring the features in the same range, it is imortant to do the feature scaling.

## Feature Scaling of Test and Train Data

In [23]:
X_Train = preprocessing.scale(X_train)
X_Test = preprocessing.scale(X_test)

## Fitting into SVM Model

In [26]:
clf = svm.SVC(kernel='rbf', C = 0.5)
clf.fit(X_Train, y_train) 
y_pred = clf.predict(X_Test)

## Evaluating the Model

In [27]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[1190  110]
 [ 225  236]]
             precision    recall  f1-score   support

          0       0.84      0.92      0.88      1300
          1       0.68      0.51      0.58       461

avg / total       0.80      0.81      0.80      1761